author: Théo Morales
title: Théo Morales
url: "https://theomorales.com"
baseurl: "/"
description: "About Théo Morales"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/DubiousCactus/home"
footer_text: "Page designed by Ankit Sultana, modified by K. Lin, and customized by Théo Morales"

sass:
  sass_dir: _sass

collections:
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "default"

nav:
  - name: "About"
    link: "/"
  - name: "CV"
    link: "CV_2026.pdf"
  - name: "Publications"
    link: "/publications"
  - name: "Blog"
    link: "/blog"
  - name: "Contact"
    link: "/contact"
